Repository YNUCPC/ynu-icpc-library, pull requests merged in 2021-11, with the labels that each got.

#38 clang-formatでフォーマットを確認するワークフローの追加
  .clang-format
  .github/workflows/clang_format.yml
  src/flow/dinic.hpp
  src/geometry/3d_intersection_of_planes.hpp
  src/graph/two_sat.hpp
  src/math/FFT.hpp
  test/aoj/1331.test.cpp
  test/aoj/2081.test.cpp
  test/aoj/2562.test.cpp
Labels: enhancement

#43 modintをiostreamに対応させる
  docs/math/modint.tex
  src/math/modint.hpp
  test/aoj/0341.test.cpp
  test/aoj/2863.test.cpp
  test/aoj/NTL_1_B.test.cpp
  test/library_checker/bitwise_and_convolution.test.cpp
Labels: documentation

#50 拡張ユークリッド互除法の追加
  docs/math.tex
  docs/math/extgcd.tex
  src/math/extgcd.hpp
  test/aoj/NTL_1_E.test.cpp
Labels: documentation

#55 Z algorithmの追加
  docs/string.tex
  docs/string/z_algorithm.tex
  src/string/z_algorithm.hpp
  test/aoj/ALDS1_14_B_rollinghash.test.cpp
  test/aoj/ALDS1_14_B_zalgorithm.test.cpp
  test/library_checker/zalgorithm.test.cpp
Labels: documentation

#57 MIT License を設定する
  LICENSE
  README.md
Labels: documentation

#60 LaTeXの書式設定の調整
  main_1col.tex
  main_2col.tex
  preamble.tex
Labels: documentation

#61 Undo つき UnionFind の追加
  docs/datastructure.tex
  docs/datastructure/rollback_unionfind.tex
  src/datastructure/rollback_unionfind.hpp
  test/library_checker/rollback_unionfind.yosupo.test.cpp
Labels: algorithm
